# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: markhobson/node-chrome


      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

          
      # run tests!
      - run: npm run test-headless
      - run: 
          name: Login to heroku docker
          command: docker login -username=$HEROKU_USERNAME --password=$HEROKU_API_KEY registry.heroku.com 
      - run:
          name: build locally
          command: docker build --rm=false -t registry.heroku.com/$HEROKU_APP_NAME/web .
      - run:
          name: push docker
          command: docker push registry.heroku.com/$HEROKU_APP_NAME/web:latest
      - run:
          name: Setup Heroku
          command: chmod +x .circleci/setup-heroku.sh
      - run:
          name: Setup Heroku
          command: .circleci/setup-heroku.sh
      - run:
          name: Deploy to Heroku
          command: heroku container:release web --app $HEROKU_APP_NAME